# Site settings
title: Ivor's Portfolio Site
description: Portfolio providing links to coding projects
#baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://ivorking.github.io/portfolio" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ivor King
user_description: Portfolio of javascript, ruby, react and HTML/CSS projects.
user_title: Junior Full Stack Developer
email: ivorking@gmail.com
twitter_username: ivorjk
github_username:  ivorking
gplus_username:  ivorking@gmail.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
